kind: PersistentVolume
apiVersion: v1
metadata:
  name: jub-pv
  namespace: jhub
  labels:
    appname: jupyterhub
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

